### ISSUE TITLE
Chef Vagrant VM fails to start

### ISSUE THREAD

**Issue by jdmurphy** [cerner/cerner_splunk#110]
Currently if you run `vagrant up chef`, it will fail with the following output:

```
==> chef: package chefdk is not installed
==> chef:  
==> chef:  
==> chef: %
==> chef:  
==> chef: T
==> chef: o
==> chef: t
==> chef: a
==> chef: l
==> chef:  
==> chef:  
==> chef:  
==> chef:  
==> chef: %
==> chef:  
==> chef: Received % Xferd  Average Speed   Time    Time     Time  Current
==> chef:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> chef: 1
==> chef: 0
==> chef: 0
==> chef:  
==> chef: 16494  100 16494    0     0  69417      0 --:--:-- --:--:-- --:--:--  383k
==> chef: Downloading Chef  for el...
==> chef: downloading http://opscode.com/chef/metadata-chefdk?v=&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
==> chef:   to file /tmp/install.sh.3240/metadata.txt
==> chef: trying wget...
==> chef: sha1	619dfe23e23b0af622052827f564a59beded7973
==> chef: sha256	66c8b0e53c8512df62d7ef7f1dcd93fddd9ec23853d2ee22ce63f7173c12a7c3
==> chef: url	https://packages.chef.io/stable/el/6/chefdk-0.12.0-1.el6.x86_64.rpm
==> chef: version	0.12.0
==> chef: downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
==> chef: Please file a bug report at http://tickets.opscode.com
==> chef: Project: Chef
==> chef: Component: Packages
==> chef: Label: Omnibus
==> chef: Version: 
==> chef:  
==> chef: Please detail your operating system type, version and any other relevant details
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I looked at the [installer script](https://chef.sh/) we were using which had a lovely comment for the metadata file being corrupt message we got:

> this generally means one of the download methods downloaded a 404 or something like that and then reported a successful exit code,
>  and this should be fixed in the function that was doing the download.

Looking further into the script, it is still using old opscode URLs which when I attempt to curl them, first 301, and then try redirecting to chef.io which causes a 404.

**Comment by acharlieh** [comment]
We're using a url that Chef, Inc still owns and [previously advertised as being valid](https://www.chef.io/blog/2015/07/16/5-ways-to-deal-with-the-install-sh-curl-pipe-bash-problem/), we need to dig into more as to why they are being non-passive to this before making a change on our side.

**Comment by acharlieh** [comment]
Also what 404? the metadata file downloaded fine, otherwise you wouldn't have gotten this data: 

    ==> chef: sha1  619dfe23e23b0af622052827f564a59beded7973
    ==> chef: sha256    66c8b0e53c8512df62d7ef7f1dcd93fddd9ec23853d2ee22ce63f7173c12a7c3
    ==> chef: url   https://packages.chef.io/stable/el/6/chefdk-0.12.0-1.el6.x86_64.rpm
    ==> chef: version   0.12.0
And the package is downloading just fine from that url for me right now... I'll check the metadata versus sha numbers.

**Comment by jdmurphy** [comment]
The 404 occurs above that. See: http://opscode.com/chef/metadata-chefdk?v=&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64. You can curl it, but a wget results in a 404. And if you look at the script specifically in the `do_download` method, it attempts wget first.

**Comment by acharlieh** [comment]
Did you remember to wrap the url in double quotes on the command line so ampersands aren't interpreted specially by bash? 

`wget "http://opscode.com/chef/metadata-chefdk?v=&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64"` seems to work fine for me, no 404s. But the script even spits out that it retrieved the metadata file successfully. It even cat it out in your output. The issue seems to be that the chef.sh version of the omnitruck script apparently expects an md5 checksum which is no longer returned in the metadata it seems. ( Line 487 of that script. look for `# check that all the mandatory fields in the downloaded metadata are there` )

**Comment by jdmurphy** [comment]
Nope, I forgot the double quotes.
