### ISSUE TITLE
Remove support for Chef 11?

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#117]
This is a question for folks using this cookbook... Should we drop support for Chef 11? 

Chef 12.0.0 was tagged 4 Dec 2014, but also we're starting to see maintenance issues as both PR #114 and PR #116 seem to have failed on Ruby 1.9.3 for Chef 12 / Ruby 2 specific issues.

Thoughts?

**Comment by acharlieh** [comment]
Shopping the idea around internally a few places, this seems like a good course. We'll increment the cookbook version to 2.0 just in case, and drop tests and some of the obvious compatibility checks.

**Comment by nmattam** [comment]
+1 to dropping support

**Comment by sambao21** [comment]
+1 but does this trigger a conversation regarding what is the general policy for support on this cookbook? 2 versions back? 1 year? on a whim?

**Comment by aaronblythe** [comment]
+1
Version bump to 2.0 should alleviate any concerns
