### ISSUE TITLE
Recipe for configuring a Heavy Forwarder

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#12]
AS A: Splunk Administrator
I WANT: The ability to setup Heavy Forwarders
SO THAT: I can offload parsing load from my Indexers, and potentially delegate control.

---

I think that #6 would help with the maintainability of this. #11 is likely a prerequisite for this.

**Comment by acharlieh** [comment]
This would also help with parsing of local timestamps globally if we're centralizing log storage.

**Comment by gravesb** [comment]
A heavy forwarder recipe was added in 2.2.0.  Closing.
