### ISSUE TITLE
Intermittent failures due to wrong ssl config passwords.

### ISSUE THREAD

**Issue by nmattam** [cerner/cerner_splunk#125]
While working on https://github.com/cerner/cerner_splunk/pull/124 it was noticed that chef-client run fails intermittently while executing the "change-admin-password" execute resource. Digging deeper into the issue this is because the encrypted form of the sslConfig password written into the server.conf file had the last two characters different from what Splunk encrypted. Since the password changed Splunk encounters issues while restartinng.

splunk_password.rb library encrypted "password" to $1$UM6cTur6RgcA whereas Splunk encrypted it to $1$UM6cTur6RgeT. This mismatch happens only for some splunk.secrets.

For this specific splunk.secret (only the first 16 characters) "qYFEHts8G0E/ABbp" the following test fails.

> Failures:
>   1) CernerSplunk::splunk_password .splunk_decrypt_password when decrypting an encrypted sslconfig password results in the original value
>      Failure/Error: expect(decrypted_password).to eq(password)
> 
>        expected: "password"
>             got: "password\x93"
> 
>        (compared using ==)
>      # ./spec/unit/libraries/splunk_password_spec.rb:26:in `block (4 levels) in <top (required)>'
> 
> > Finished
> 
>  in 9.15 seconds (files took 4.39 seconds to load)
> 2 examples, 1 failure
> Failed examples:

I wasn't able to find the pattern of splunk.secrets that causes this issue. I might have the fix for this issue but waiting for more splunk.secrets to cause this again so that I can confirm my fix works.

If you hit this issue, manually updating the server.conf with the old encrypted password (which you can find from the diff generated during the chef-client run) and restarting Splunk should help.

**Comment by nmattam** [comment]
It seems pass4SymmKey was also causing problems as the captain (in my SHC) was not able to talk to the members (intermittently) since different pass4SymmKey was set on some members.

**Comment by acharlieh** [comment]
Fixed with 6130efd71476070896447fa0513dabf28222a2b7
