### ISSUE TITLE
Unnecessary pessimistic constraint on patch version

### ISSUE THREAD

**Issue by EdwardSkoviak** [cerner/cerner_splunk#133]
There's an unnecessary pessimistic constraint on a patch version of the ulimit cookbook. This should be lifted so 0.4 can be used.

**Comment by gravesb** [comment]
After the changes from #96 we may not even need the ulimits cookbook anymore since splunk doesn't honor the values we're setting anyway.  It's probably better to just remove that dependency entirely.
