### ISSUE TITLE
Dynamic host discovery

### ISSUE THREAD

**Issue by jeffzjd** [cerner/cerner_splunk#138]
We have a use case in which the host on which we configure a Splunk forwarder (using this cookbook) is different than the host where it's eventually deployed. 

In order to associate the logs with the correct host, we'd like to submit a request to add the ability to dynamically inject current hostname into the forwarder configuration (i.e. inputs.conf) whenever splunkd starts or restarts.

**Comment by acharlieh** [comment]
@jeffzjd Are you preparing a system image as opposed to building a running system? In which case wouldn't you after your chef-client run, stop Splunk and run `$SPLUNK_HOME/bin/splunk clone-prep-clear-config` as described in [Splunk's documentation](http://docs.splunk.com/Documentation/Forwarder/latest/Forwarder/Makeauniversalforwarderpartofahostimage)? When Splunk starts up the next time (when it restarts on the cloned image) it'll pick up whatever the hostname is at start time.

**Comment by jeffzjd** [comment]
@acharlieh Thanks for pointing out the right direction. Yes, we're using the cookbook to prepare an application image. And since we have multiple applications (images) that require this kind of handling, I think it might still make sense if we can get first class support from this cookbook.

**Comment by acharlieh** [comment]
We'd welcome a pull request for it. Offhand I think the best design would be an additional recipe with a ruby block resource that does nothing but notifies the Splunk service to stop and deletes the marker file (so Splunk doesn't start up again with the delayed notification at the end). Then calls an execute resource to invoke the prep command as the operating system user that Splunk runs as. This way we don't impact any existing code and leveraging such functionality would be as easy as just tacking another recipe on the end of the run list
