### ISSUE TITLE
Must Specify Domain/ Password on windows execute resources

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#142]
With Chef 12.19.8 (Stable version 12.19.33) a change was made such that on windows the execute resource requires that a password is specified when a user is on the execute resource. (Commit: chef/chef@c6e87d9655617d7d4b334b3e565cdac3abe443b0 PR: chef/chef#5764 )

The side effect of this means errors and sadness for us until resolved: https://travis-ci.org/cerner/cerner_splunk/jobs/204316050#L1075

We perhaps need to add attributes for specifying domain, and a chef-vault for a password to use for the user on Windows. (And in general a lot of other windows work needs to happen as well for running the service as someone other than the local system account.)

Fun note though the splunk-first-run command that Travis blew up on at https://github.com/cerner/cerner_splunk/blob/2.9.0/recipes/_install.rb#L75 will in fact never execute on windows because the MSI does the first run, thus no ftr file is to be found. There might be other ones that would execute, but this is the first it seems to encounter.

**Comment by gravesb** [comment]
Added chef-vault support for specifying a windows user password in #174. Closing.
