### ISSUE TITLE
Failure when using cerner_splunk_forwarder_monitors inside a separate run_context

### ISSUE THREAD

**Issue by tboettch** [cerner/cerner_splunk#18]
When the ```cerner_splunk_forwarder_monitors``` resource is used inside a run_context other than the top-level context (e.g. from a provider that declares ```use_inline_resources```) it is unable to send notifications to the "splunk" service because that Chef resource is not visible. To avoid this, the ```cerner_splunk_forwarder_monitors``` should declare a copy of the service resource.

**Comment by acharlieh** [comment]
More design thoughts: https://github.com/cerner/cerner_splunk/pull/22#issuecomment-124629692
