### ISSUE TITLE
Error running cerner_splunk on Chef 10.24.0

### ISSUE THREAD

**Issue by barkerd427** [cerner/cerner_splunk#20]
This is the output from the run: https://gist.github.com/barkerd427/6bbf59d7fffc7d118bfb

This was on RHEL. There were previous issues with including an outdated cookbook for splunk, but it didn't look like it had been run before cerner_splunk. I think the cookbook should handle directory validation prior to this point.

**Comment by acharlieh** [comment]
@barkerd427 Try out the cookbook currently in at the head of the stable branch, I'm working on putting up the release review for 1.7.0 now.

**Comment by barkerd427** [comment]
@acharlieh It works!!! Thanks for getting this out this week.

**Comment by acharlieh** [comment]
@barkerd427 Excellent! Thank you for helping us check things! Closing this issue as [v1.7.0](https://github.com/cerner/cerner_splunk/issues?q=milestone%3Av1.7.0) is [tagged](https://github.com/cerner/cerner_splunk/releases/1.7.0) uploaded to [supermarket](https://supermarket.chef.io/cookbooks/cerner_splunk/versions/1.7.0), and uploaded to all internal enterprise chef servers.
