### ISSUE TITLE
Initial Cookbook Execution Fails if SPLUNK_OS_USER is root when Splunk is Installed

### ISSUE THREAD

**Issue by wheatevo** [cerner/cerner_splunk#207]
If an existing splunk installation exists with SPLUNK_OS_USER is set to `root` within `/opt/splunkforwarder/etc/splunk-launch.conf`, the splunk-first-run execute step will fail.

This occurs when the `node['splunk']['user']` user (`splunk` in this case) is unable to use setuid to act as the SPLUNK_OS_USER.

Example output:
```
  * execute[splunk-first-run] action run[2019-11-25T09:01:40-06:00] INFO: Processing execute[splunk-first-run] action run (cerner_splunk::_install line 103)
    [execute]
               Changing to bootstart user failed. Please run splunk ftr as bootstart user.

    ================================================================================
    Error executing action `run` on resource 'execute[splunk-first-run]'
    ================================================================================
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/splunkforwarder/bin/splunk help commands --accept-license --answer-yes --no-prompt --seed-passwd 'changeme' ----
    STDOUT:
    STDERR: Changing to bootstart user failed. Please run splunk ftr as bootstart user.
    ---- End output of /opt/splunkforwarder/bin/splunk help commands --accept-license --answer-yes --no-prompt --seed-passwd 'changeme' ----
    Ran /opt/splunkforwarder/bin/splunk help commands --accept-license --answer-yes --no-prompt --seed-passwd 'changeme' returned 1
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cerner_splunk/recipes/_install.rb
    103: execute 'splunk-first-run' do
    104:   command run_command
    105:   user node['splunk']['user']
    106:   group node['splunk']['group']
    107:   if Gem::Version.new(Chef::VERSION) >= Gem::Version.new('12.19.33')
    108:     password windows_password if platform_family?('windows')
    109:   end
    110:   only_if { ::File.exist? "#{node['splunk']['home']}/ftr" }
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/cerner_splunk/recipes/_install.rb:103:in `from_file'
    execute("splunk-first-run") do
      action [:run]
      default_guard_interpreter :execute
      command "/opt/splunkforwarder/bin/splunk help commands --accept-license --answer-yes --no-prompt --seed-passwd 'changeme'"
      backup 5
      declared_type :execute
      cookbook_name "cerner_splunk"
      recipe_name "_install"
      domain nil
      user "splunk"
      group "splunk"
      only_if { #code block }
    end
```

Contents of `/opt/splunkforwarder/etc/splunk-launch.conf` (comments removed):
```
SPLUNK_HOME=/opt/splunkforwarder
SPLUNK_SERVER_NAME=SplunkForwarder
SPLUNK_WEB_NAME=splunkweb
SPLUNK_OS_USER=root
```

**Comment by gravesb** [comment]
In what scenario would a Splunk installation exist where the Splunk service was never started, but the splunk-launch.conf file was edited?  If you're trying to converge on an existing node with other manual changes present, there are likely a number of things that could have been done that would prevent this cookbook from working. I'm not sure it makes sense to try to account for them all here.

**Comment by wheatevo** [comment]
@gravesb 

We have seen this circumstance on nodes that were provisioned with Splunk in the past (via a non-Chef method) that are running the cerner_splunk cookbook for the first time. I am reaching out to one of the people that encountered the issue to see if he is able to gather a full log of the Chef run that failed.

I agree that accounting for all possibilities is probably unnecessary, but in this case the resolution is fairly simple and is directly related to the following step (since we are attempting to start the service as the splunk user it makes sense to first ensure it can be started by the splunk user).

For now I will attempt to gather more information on the issue as well as the original state of the node.

**Comment by gravesb** [comment]
Given the specificity of the issue, I think you're better off creating a custom recipe and adding it to your runlist prior to cerner_splunk. I don't see this functionality affecting/benefitting the vast majority of our consumers.

**Comment by wheatevo** [comment]
@gravesb 

We can do that, thank you for the feedback.
