### ISSUE TITLE
Cookbook cannot be used with Chef 15

### ISSUE THREAD

**Issue by wheatevo** [cerner/cerner_splunk#208]
The current cookbook cannot be used with Chef 15 due to the chef_version constraint within the metadata.rb.

Since there are few deprecations in Chef 15, most of this change will likely involve uplifting testing to also cover Chef 15.

https://docs.chef.io/chef_deprecations_client.html

**Comment by gravesb** [comment]
This was fixed back in 2.36.0. Closing.
