### ISSUE TITLE
cookbook stopped working with chef 12 due to chef-vault version

### ISSUE THREAD

**Issue by brightskylee** [cerner/cerner_splunk#211]
This cookbooks' Gemfile restrict chef-vault version to be `> 3.0` thus it'll pull whatever the latest chef-vault gem version. 

In the most recent release of chef-vault gem they dropped support for ruby 2.2/2.3 so this cookbook stopped working with chef 12 anymore. 

We need a fix the for a more granular control of chef-vault gem version based on chef version.

**Comment by david-crowder** [comment]
I don't think the issue here is the Gemfile, but rather an issue in the upstream chef-vault cookbook the splunk cookbook depends on:
https://github.com/chef-cookbooks/chef-vault/pull/75

**Comment by brightskylee** [comment]
@david-crowder Yes you are right. My apology. It's the upstream chef-vault cookbook that pulls in the 4.x chef-vault gem. cerner_splunk cookbook is not installing the chef-vault gem directly.

I guess we should need to wait for the fix for chef-vault cookbook to be released.

**Comment by gravesb** [comment]
Also as pointed out on that linked issue, Chef 12 has been EOL for nearly 2 years so you should look into upgrading to a newer Chef version.
