### ISSUE TITLE
line cookbook version not accurate

### ISSUE THREAD

**Issue by bpcook61** [cerner/cerner_splunk#230]
The current version released has the following specified in the metadata.rb for the line cookbook dependency.
```
depends          'line', '~> 2.0'
```
This isn't correct, as version 2.0.0 and 2.0.2 don't have the filter_lines resource that is used in the cerner_splunk cookbook.  My guess would be that the dependency needs to be:
```
depends          'line', '~> 2.1'
```

**Comment by gravesb** [comment]
Thanks, submitted https://github.com/cerner/cerner_splunk/pull/231 to fix it.
