### ISSUE TITLE
install recipe fails to restart splunk service when upgrading from 7.3.x

### ISSUE THREAD

**Issue by lancefriday945** [cerner/cerner_splunk#235]
On the latest version of splunk, splunkforwarder needs to be restarted through /opt/splunkforwarder/bin/ via ./splunk restart command.

**Comment by gravesb** [comment]
Is this a persistent node where the version of Splunk is being upgraded?

https://docs.splunk.com/Documentation/Splunk/8.1.2/Admin/RunSplunkassystemdservice#Upgrade_considerations_for_systemd

**Comment by lancefriday945** [comment]
Yeah. It looks like its installing a new forwarder so should only be a one time failure?

**Comment by gravesb** [comment]
Yes, it is directly related to the upgrade.  Once Splunk has been started correctly, the cookbook should work fine from there on.  I'm considering trying to add something to the cookbook to handle this upgrade scenario , but I haven't gotten to it yet.

**Comment by lancefriday945** [comment]
Thanks for the update!

**Comment by gravesb** [comment]
This issue is addressed in #239.
