### ISSUE TITLE
Proposal around PR / Merge process

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#41]
So I was thinking about this a bit... What if when we merge PRs, instead of just pressing the button, we manually merge locally and as part of completing this merge, we increment the metadata in the fix version. ... But in that manner, we're "releasing" a new version with each PR merge, but we only upload to supermarket when we do a process release (and all the internal paperwork, to increment the enhancement version)? 

We could then make stable the main branch of the repository (since each checkout would be "releasable"... you might get newer features than what's in supermarket / signed off on, but since we'd have unique fix versions for each incremental change to stable, this isn't as much of a problem. Downloading master for the latest signed off version would still be an option, and when a new signed off version is released, the version number won't conflict. 

Thoughts? :+1: / :-1: ?

**Comment by garrypolley** [comment]
I'm a little confused, and this may be my lack of understanding on the entire ecosystem.  

Does using the button and then making a released tag not work?  Even if we end up with a bunch of minor version tags that seems more desirable than having to cut a release for every pull request.  Though it could end up being a release for each pull request anyway, but that's a different discussion to me.  By doing the merge via github it makes it easier to follow, and we could eventually start using milestones and tie those in. Then we'd have an idea of what the plan is for each version as we move forward.

**Comment by acharlieh** [comment]
I'm not proposing adding a tag or doing a process release for every pull request. But rather just updating metadata.rb as part of the merge of each PR. (It doesn't belong as part of the PR branch, because that incrementing is a function of the order that the PRs are ultimately merged). But the benefit to this is that someone could incrementally install every intermediate change of the cerner_splunk cookbook if they so chose and not get into the "Well I installed 1.7.0"... what set of changes do I have?

We initially made master the released code and default branch to people from accidentally winding up in the multiple different versions of the same cookbook. And people doing that and pulling a not-quite-working version is still a risk, but it'll be guaranteed to be a unique version from the "official" tagged and uploaded to supermarket milestones. 

If a fix is significant enough, we may choose to tag, milestone and release a fix version, and this doesn't preclude that. 

@garrypolley does this thought process make more sense?

**Comment by garrypolley** [comment]
@acharlieh  Thanks for clarifying.  That does make more sense. 

I like the merge button.  Personally I would do a merge button, then go and update the metadata.rb file on master.  To me that makes it easier to keep the contributor in the history.  In my ideal world I could just modify the branch right before I merged it in, but I don't think that's always an option.

**Comment by acharlieh** [comment]
That might be easier, but history would be dirtier, and you wind up with these in-between states where after push button, before version increment that someone could clone. I would still propose keeping the contributor in history though!

Instead of push button... the process would be something like the following:
1) `git fetch origin pull/ID/head:BRANCHNAME` [reference](https://help.github.com/articles/checking-out-pull-requests-locally/)
2) `git merge --no-commit BRANCHNAME`
3) update metadata.rb
4) add / commit / push.

(this way you keep all the commits of the branch, AND make the change to metadata.rb before any push to the stable / main branch occurs)

**Comment by garrypolley** [comment]
:+1:   I like it!

**Comment by acharlieh** [comment]
It's true... I'm sad about not being able to use the merge button too, however, I feel like the usefulness of the repository would be vastly improved for others (solving the default branch problems, and enabling safer checkout, upload and try) and the pain felt by no merge button would be limited to myself and @david-crowder. If there's consensus, I would propose that this start immediately after 1.8.0 is released under the existing process. (As the release PR would just not include the next version commit to start adopting the new process.)

**Comment by acharlieh** [comment]
Merged with f5b698efd4e4458c8cd400b63292faf07aa7b688 but as mentioned above the new process will come into effect with the Release PR for 1.8.0
