### ISSUE TITLE
Define tags

### ISSUE THREAD

**Issue by bbaugher** [cerner/cerner_splunk#43]
I would be great if I could use the cookbook to define tags for things like the host or other more nebulous things like sources or even an index. I would also like to be able to define permissions to make the tag readable to everyone.

Currently doing all of this through the webui is awful.

**Comment by acharlieh** [comment]
Something I would like to have someone look into at some point is if it is possible to define an extra index time metadata field (just like host, source, and sourcetype, but custom) to enable people to have a way to group data together through chef-client with data that does not have to appear in the logs being monitored. I think this would involve the `_meta` attribute on the [inputs.conf stanza](http://docs.splunk.com/Documentation/Splunk/6.0.6/admin/inputsconf) and possibly other files there. 

Now with regards to creating tags outside of the WebUI, I suspect there is an ability to create tags in apps through the [REST API](http://docs.splunk.com/Documentation/Splunk/6.0.6/RESTAPI/RESTknowledge#POST_search.2Ftags.2F.7Btag_name.7D). (I believe you'd want to use the /servicesNS/nobody/{app_name}/search/tags/{tag_name} endpoint). Assuming that does not create the tag being visible to everyone, I have noticed there seems to be an (undocumented?) /saved/fvtags endpoint that seems to have the [`eai.acl` fields](http://docs.splunk.com/Documentation/Splunk/6.0.6/RESTAPI/RESTintro#EAI_response_data) that might be able to be updated [like other objects](http://answers.splunk.com/answers/115781/change-the-owner-of-a-saved-search-via-rest.html).  (I found it looking at the [/servicesNS/-/-/directory endpoint](http://docs.splunk.com/Documentation/Splunk/6.0.6/RESTAPI/RESTknowledge#GET_directory)).

**Comment by acharlieh** [comment]
Now with regards to configuring through chef-client... we are now able (with the resolution of #1 ) able to define tags in [tags.conf](http://docs.splunk.com/Documentation/Splunk/6.0.6/admin/tagsconf) files in apps on the search heads in each environment. (A pull request to our chef-repo, and then us running chef-client on the search head would make the change).

**Comment by acharlieh** [comment]
@bbaugher are either of these ideas (REST, existing chef abilities) what you're looking for? Or are you looking for something else?

**Comment by bbaugher** [comment]
Any of the implementations sound like they would work. The one option sounds like we would have to coordinator with your team and your chef config. I'm not particularly fond of this but seems pretty easy for now. Did you have a preference?

**Comment by acharlieh** [comment]
Not particularly. The REST API method would put more control in your hands, and is the closest to automating the web-ui interactions. (we'd just ask that you don't DDOS us :grin:), The other method would indeed require coordination with us (as it's running chef-client on the servers (search heads) that we're responsible for. When some of our continuous (automated) deployment stories are completed toward the middle to end of this year, hopefully that will become as easy as a pull request.

**Comment by bbaugher** [comment]
You can close this as we are doing this today using jenkins

**Comment by acharlieh** [comment]
Closing question per comment :)
