### ISSUE TITLE
Reset to default app settings

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#50]
Building on top of #37, it might be neat if there was an option to loop through the configuration that comes with the app, and to edit all local configurations to remove corresponding stanza configurations that conflict or override. (The thought is someone tries something out in the UI, but then we install an app, and they are cleanly set back to the defaults). 

More thought would have to put into place, so that we don't obliterate any local configuration added by chef, and we only obliterate those pieces that override things, although a kill all option could be a good first pass.

**Comment by gravesb** [comment]
While this is an interesting idea, it's not really something I've had much use for in recent history.  The amount of work this would take to implement would likely outweigh the benefits of it. Closing.
