### ISSUE TITLE
App bags All The Way Down

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#54]
It would be useful if we could include data bags indefinitely down the chain. Top levels being the cluster bag and attributes, but each inclusion could specify an additional bag to include as a parent (base that's overridden). 

We'd have to make sure we keep track of the loaded coordinates so that we have no cycles.

**Comment by gravesb** [comment]
The current level of bag nesting seems sufficient for our current use cases. Closing since this 'nice to have' isn't likely to see the light of day.
