### ISSUE TITLE
Use Search for discovery of Cluster Members

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#6]
How cool would it be if search heads could find cluster masters. Cluster slaves could find cluster masters, and forwarders could find cluster slaves all without explicitly listing the same in the data bags?

We'd still need the fallback option of being able to list receivers explicitly (when spread across multiple chef servers or organizations), but wouldn't that be neat?

**Comment by gravesb** [comment]
Current functionality seems sufficient.  Closing as this is unlikely to get completed.
