### ISSUE TITLE
Remove Aeon forwarder cleanup

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#60]
With 1.10.0 of the cookbook, we started relying on other cookbooks (namely [xml](https://github.com/opscode-cookbooks/xml) and [chef-vault](https://github.com/opscode-cookbooks/chef-vault)) to manage chef-gems. See #49, #58, and e46853228f95eb06e684da4b0699277afcca0eb3 and e0bc1576790cef679d9a16954f1a4a49eb8064d6. 

I didn't realize until this morning, is that this completely breaks Chef 10 users. chef-vault cookbook calls require chef-vault immediately after chef_gem resource so [we'd run into this issue](https://github.com/Nordstrom/chef-vault/issues/102). But before that, it [requires lwrpbase](https://github.com/opscode-cookbooks/chef-vault/blob/d90090b28fbf4108e4232fb309001e723384533f/libraries/chef_vault_secret_resource.rb#L19) The xml cookbook, installing native dependencies, you'd run into opscode-cookbooks/build-essential@2bc962e10fa65f63dc586dca8dc83895ef41e6f7 if you're installing a license master. 

Proposal therefore, is to say that 1.9.0 is the last supported chef 10 version. We should then remove all chef 10 pieces (vagrant box, aeon cookbook cleanup). and put instructions that anyone upgrading from chef 10 should run with 1.9.0 first, and then get to chef 11+ and then upgrade to the latest cookbook.

**Comment by david-crowder** [comment]
+1

**Comment by nimeshsubramanian** [comment]
+1

**Comment by garrypolley** [comment]
non-passive changes should be a major version upgrade right?  

Assuming this follows [semantic versioning](http://semver.org/)

**Comment by acharlieh** [comment]
@garrypolley Indeed. Unfortunately 1.10.0 was already cut before I realized this, but Next should take a major version bump.

**Comment by garrypolley** [comment]
> do we press forward and remove it

This is my recommendation. 

> One could also make an argument that removing support for a no longer supported version of a dependency isn't as non-passive of a change.

:smiley_cat:  I can that.  It's clearly documented as 11+ however it did still support 10. So it's really depends on how serious we are about versioning.

**Comment by acharlieh** [comment]
While we removed the vagrant box with this release, we'll also want to remove the aeon cleanup. Keeping this open, but just not on a milestone for those changes.

**Comment by gravesb** [comment]
The aeon cleanup recipe was removed in version 2.21.0. Closing.
