### ISSUE TITLE
Allow for configuring limits.conf

### ISSUE THREAD

**Issue by bbrownz** [cerner/cerner_splunk#63]
We've ran into an issue where we have a large volume of logs coming from a single node (specifically hadoop job information) the volume of information has exceeded the default maxKBps allowed by the limits.conf. 

It would be handy if this file was added to the conf files that can be configured through the splunk config template.

**Comment by bbrownz** [comment]
The PR for this change can be found at #62

**Comment by acharlieh** [comment]
As it seems like we're just dropping stanzas into a file, what about using the apps functionality that was introduced in v1.9.0 to manage this file?

**Comment by bbrownz** [comment]
I'm not sure I follow. Wouldn't the limits apply only to the application itself (like modifying the maximum number of rows in a PDF)? For example with the universal forwarder if I installed an app with the forwarder, that limit would only apply to the app, it doesn't seem like it would effect the forwarder itself. That would be a different application wouldn't it?

**Comment by acharlieh** [comment]
Not quite... Splunk combines configuration files from all enabled apps and the system, in two different ways depending on your context. This is [described in detail in the docs](http://docs.splunk.com/Documentation/Splunk/latest/Admin/Wheretofindtheconfigurationfiles), but briefly when you have an app/user context (such as when you're searching), the current user's settings in each stanza win, followed by settings in the current app, followed by settings exported by other apps and finally the base system. 

When you have no app/user context for the settings, and are working on settings that apply instance wide (such as when you're ingesting files, or authenticating against LDAP), Splunk resolves these settings in a global context, where settings in the local system directory wins, followed by all local enabled apps, followed by all default enabled apps, followed by the default system. 

Now limits such as the number of rows in a PDF, that could be a search time configuration, but how fast logs are sent from the UF to the indexer that sounds like a global setting (in spite of what the docs say about limits.conf being an app/user context file only). To give more credence to this idea, you'll notice that the effective maxKBps setting that you wind up with on your UF itself in fact comes from the limits.conf in the default directory of the SplunkUniversalForwarder app. If you peek in $SPLUNK_HOME/etc/system/default/limits.conf you'll see the value set there is actually 0 (unlimited). (and this is the value we would want to likely keep on our Splunk servers). Finally if we were managing forwarders using the [Deployment Server](http://docs.splunk.com/Documentation/Splunk/6.2.3/Updating/Aboutdeploymentserver), distributing apps would be the only way we would be able to manage configuration on the forwarders :)

**Comment by bbrownz** [comment]
OK, I think I'm following now. So for our particular issue with the forwarders it seems like the most appropriate place to modify the maxKBps would be in the local folder of the universal forwarder

$SPLUNK_HOME/etc/apps/SplunkUniversalForwarder/local/limits.conf

That document around configuration precedence makes the issue somewhat confusing though. When running in an app context (which you would assume that the forwarder would be) the precedence should be any configuration in the app (local followed by default) with system coming last (local followed by default). In our case though we landed a limits.conf as a short term solution in the system local configuration directory, and I can say for sure that this updated the maxKBps for the forwarder. In this case it seems like the observed precedence order for the forwarder is actually system local, app default, system default. This matches the order for the global context.

Do we have a method today to add a limits file to the local directory of the forwarder without the deployment server? If we don't should I make the PR for this issue more specific to the forwarders, or make it more applicable to other potential use cases by leaving it as is?

**Comment by acharlieh** [comment]
> When running in an app context (which you would assume that the forwarder would be)

Out of curiosity, what lead you to assume that the forwarder should be an app context? (This may be knowledge that we need to get out wider, or revisions to Splunk's docs we could propose) Most of the time the universal forwarder is, as you found out, a global context.

> Do we have a method today to add a limits file to the local directory of the forwarder without the deployment server?

We do indeed! [the apps hash](https://github.com/cerner/cerner_splunk/blob/1.6.0/docs/databags.md#apps-hash) introduced in v1.6.0 can be configured through [attributes](https://github.com/cerner/cerner_splunk/blob/1.6.0/docs/attributes.md) to manage arbitrary conf files in app directories. (Actually I notice that the current version of the attributes doc is outdated since as of v1.9.0 we can download apps). But this is indeed for any Splunk instance, so if you want to drop your override of the limits.conf into the SplunkUniversalForwarder app, you'd need to add something like the below to your node attributes. (This is JSON of course, you may want the ruby equivalent, depending on how you're managing setting attributes on your nodes):

```json
{
  "splunk": {
    "apps": {
      "SplunkUniversalForwarder": {
        "local": true,
        "files": {
          "limits.conf": { "thruput": { "maxKBps": "0" } }
        }
      }
    }
  }
}
```

Additionally if you want to ensure your local limits.conf is removed, make that file an empty hash (or empty string...)

```json
{
  "splunk": {
    "apps": {
      "SplunkUniversalForwarder": {
        "local": true,
        "files": {
          "limits.conf": { }
        }
      }
    }
  }
}
```

**Comment by bbrownz** [comment]
Awesome, thats good info, thanks Charlie. This solves my particular use case, unless you want the PR for the more general outside of an app configuration we should be able to close out this issue and PR.

**Comment by acharlieh** [comment]
As you're happy for your use case, I'm going ahead and closing this.
