### ISSUE TITLE
Clean the Fishbucket

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#71]
AS AN: Owner of a Splunk Forwarder
I WANT: The ability to clean (selectively or completely) the fishbucket
SO THAT: I can reindex files when needed.

This post has a number of methods to it:
http://answers.splunk.com/answers/72562/how-to-reindex-data-from-a-forwarder.html

Probably enable/configure through attributes? (after package install, before configuration changes)

Likely want to spit out a warning invoke a warning log resource so that if this is enabled we can see it (otherwise reindex with every chef run _eep_)

**Comment by bby-bishopclark** [comment]
The original article URL is dead because Splunk may think history is bad, and deleted it.

The article here has insight:
https://answers.splunk.com/answers/413892/how-do-i-force-a-universal-forwarder-to-reindex-al.html

```
Hi daniel333,

btool is used to view or validate Splunk config files. 
Probably btprobe was meant in the previous answer, which enables you to remove fish bucket information for a specific file. 
Easiest way to re-index all inputs on a universal forwarder is to delete the fish bucket index while Splunk UF is stopped:

  $SPLUNK_HOME/bin/splunk stop
  rm -rf $SPLUNK_HOME/var/lib/splunk/fishbucket
  $SPLUNK_HOME/bin/splunk start

Splunk will re-create the fish bucket index and immediately re-index all the inputs on your universal forwarder, so watch out for your license usage ;)

cheers, MuS
```

It sounds like this feature can be delivered relatively easily:
```
file "#{node['splunk']['home']}/var/lib/splunk/fishbucket" do
  action :delete
  notifies :restart, "service[splunk]"
  only_if { node.read('splunk', 'forwarder', 'reindex') }
end
node.normal['splunk']['forwarder'].delete('reindex') rescue nil
```
.. or so.

**Comment by gravesb** [comment]
I haven't really had a desire for this feature in the recent past.  Closing since we will likely never address this.
