### ISSUE TITLE
Configuration Option to Reclaim Disk Space

### ISSUE THREAD

**Issue by acharlieh** [cerner/cerner_splunk#78]
When an index is unconfigured, the buckets remain on disk, it'd be neat if we could have a configuration option (attribute, data bag entry) with which after splunk is restarted to remove configuration files, we could reclaim the disk for specified indexes.

We would want a check to make sure the index is not actually configured, but this would be helpful.

**Comment by gravesb** [comment]
I can see this being useful, but in practice the removal of indexes is rare.  Even more-so removal with the desire to immediately delete all the data on disk.  Furthermore, we would likely need to handle this differently for smart store enabled indexes.  I don't believe the benefits that would come from this would outweigh the efforts involved to implement it. Closing.
