### ISSUE TITLE
Separate Databag module into a separate Gem project

### ISSUE THREAD

**Issue by aaronblythe** [cerner/cerner_splunk#97]
I believe that the https://github.com/cerner/cerner_splunk/blob/stable/libraries/databag.rb has utility beyond this project and we should discuss the merits of separating this into another project.  

Possibly this module would live in a gem that can be required by other cookbook projects.

Possibly this module would live in a gem/cookbook hybrid similar to https://github.com/sethvargo/chef-sugar

Maybe there are other things in the library folder that should also be separated for better reuse, however this databag paradigm is the particular thing that I would like to reuse currently outside of this project.

**Comment by acharlieh** [comment]
:+1: ... it was indeed always the intention that a lot of those parts would eventually be reusable, but it was developed inline to start with a use case that was being developed along side.

**Comment by gravesb** [comment]
Given that this hasn't had any activity in 6 years, I think it's safe to say it's never going to happen. Closing.
